version: '3.1'
#
services:

  bacula-fd:
    network_mode: host
    image: fametec/bacula-client:11.0.5
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9102:9102
# 
#volumes: 
#  pgdata:
#
#  gmail:
#    image: fametec/postfix:gmail
#    restart: unless-stopped
#    depends_on:
#      - bacula-dir
#    # ports:
#    #  - 30025:25
#    environment:
#      GMAIL_USER: xxxxxxxx
#      GMAIL_PASS: xxxxxxxx
#
#  smtp2tg:
#    image: b3vis/docker-smtp2tg
#    restart: unless-stopped
#    volumes:
#      - ./etc/smtp2tg.toml:/config/smtp2tg.toml:ro
#    #    ports:
#    #  - "31025:25"
#    depends_on:
#      - bacula-dir
#
# 
#volumes: 
#  pgdata:
